"""empty message

Revision ID: 0d898561e71d
Revises: 
Create Date: 2020-01-05 04:48:14.248851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d898561e71d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('KeranjangDetails', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('KeranjangDetails', sa.Column('produk_id', sa.Integer(), nullable=False))
    op.drop_constraint('KeranjangDetails_ibfk_2', 'KeranjangDetails', type_='foreignkey')
    op.create_foreign_key(None, 'KeranjangDetails', 'Produk', ['produk_id'], ['id'])
    op.drop_column('KeranjangDetails', 'barang_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('KeranjangDetails', sa.Column('barang_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'KeranjangDetails', type_='foreignkey')
    op.create_foreign_key('KeranjangDetails_ibfk_2', 'KeranjangDetails', 'Produk', ['barang_id'], ['id'])
    op.drop_column('KeranjangDetails', 'produk_id')
    op.drop_column('KeranjangDetails', 'deleted')
    # ### end Alembic commands ###
