"""empty message

Revision ID: 137afd83cd85
Revises: 83cf51ac3d67
Create Date: 2020-01-14 12:45:06.564585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '137afd83cd85'
down_revision = '83cf51ac3d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FotoProduk')
    op.drop_index('user_id', table_name='Penjual')
    op.drop_table('Penjual')
    op.drop_column('KeranjangDetails', 'penjual_id')
    op.add_column('Produk', sa.Column('foto_produk', sa.String(length=1000), nullable=False))
    op.drop_constraint('Produk_ibfk_1', 'Produk', type_='foreignkey')
    op.drop_column('Produk', 'penjual_id')
    op.drop_constraint('Transaksi_ibfk_2', 'Transaksi', type_='foreignkey')
    op.drop_column('Transaksi', 'penjual_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transaksi', sa.Column('penjual_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('Transaksi_ibfk_2', 'Transaksi', 'Penjual', ['penjual_id'], ['id'])
    op.add_column('Produk', sa.Column('penjual_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('Produk_ibfk_1', 'Produk', 'Penjual', ['penjual_id'], ['id'])
    op.drop_column('Produk', 'foto_produk')
    op.add_column('KeranjangDetails', sa.Column('penjual_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_table('Penjual',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('nama_toko', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('lokasi', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name='Penjual_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'Penjual', ['user_id'], unique=True)
    op.create_table('FotoProduk',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('produk_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('foto_produk', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['produk_id'], ['Produk.id'], name='FotoProduk_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
