"""empty message

Revision ID: 83cf51ac3d67
Revises: 0d898561e71d
Create Date: 2020-01-05 22:42:09.733015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83cf51ac3d67'
down_revision = '0d898561e71d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('KeranjangDetails', sa.Column('penjual_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('KeranjangDetails', 'penjual_id')
    # ### end Alembic commands ###
